version: '3'
services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    build:
      context: ../server
    ports:
      - '5000:5000'
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - '27017:27017'

